---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Install codimd
      helm:
        chart:
          name: hackmd
          version: 1.2.1
          source:
            type: repo
            location: https://kubernetes-charts.storage.googleapis.com
        name: codimd
        namespace: codimd
        state: present

