#- name: lvm2 installed
#  apt:
#    name: lvm2
#
- name: Copy exmaple config
  copy:
    src: lvmd.yaml
    dest: /etc/topolvm/lvmd.yaml

- name: Get lvmd.service file
  get_url:
    url: https://raw.githubusercontent.com/topolvm/topolvm/v0.5.3/deploy/systemd/lvmd.service
    src: "{{ role_path }}/files/lvmd.service"
    dest: /etc/systemd/system/lvmd.service
    owner: root
    group: root

- name: lvmd.service started
  systemd:
    name: lvmd.service
    enabled: yes
